trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
# Build release
- script: docker-compose up -d
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Visual Studio Enterprise (94065302-e183-4130-919d-f3bee7d40990)'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Push services'

